### PR TITLE
optimize font loading.

### PR DESCRIPTION
**Pull request by ctalkington**
cc @jarrodtaylor @mwi-michelle

### CODE REVIEW

**Comment by ctalkington** [comment]
@jarrodtaylor can we go ahead and release the current develop branch? the blog posts were lost last time around so i want to be sure we get those back live ASAP. there are a few areas we want to improve yet but those will come with time and whats ready is a big improvement.

**Comment by jarrodtaylor** [comment]
@ctalkington I'll look into a release today.

It looks like all the blog posts are there. Sometimes you'll see duplicates in dev if they don't all get cleared when rebuilding. Prod releases start fresh, so they won't have duplicates. There should be somewhere around 120 posts.

**Comment by ctalkington** [comment]
@jarrodtaylor  thanks i was referring to production missing blog posts. see here:

https://github.com/Syrinx/Syrinx.github.io/commit/50a67aea1798c1ea6adb6751484a3383d0854caf
https://github.com/Syrinx/Syrinx.github.io/tree/master/blog

example of missing:

http://www.syrinx.com/blog/The-Future-of-voice-recognition-software.html

**Comment by jarrodtaylor** [comment]
@ctalkington Gotcha. Okay, it's deployed now.

Looks like [this post](http://www.syrinx.com/blog/syrinx-cardis-ink-deal-to-make-low-value-e-payments-profitable-for-fuel-and-c-stores.html) is still getting tripped up. The file is there though, so it might be a casing issue or something.

**Comment by ctalkington** [comment]
@jarrodtaylor thanks. the only issue im seeing is for some reason the sitemap.xml doesnt get copied across to master. any thoughts?

**Comment by jarrodtaylor** [comment]
The `deploy` task just copies `/dist`. Probably an async timing issue.

It looks like `buildSitemap` is returning before it writes the sitemap.xml file, which in turn kicks of the `deploy` task too early. 

I added a console log of "writing sitemap" to see where in the process sitemap.xml is being written.

Shortened for brevity:

```bash
[14:19:10] Starting 'buildAssets'...
[14:19:10] Finished 'buildAssets' after 79 ms
[14:19:10] Starting 'buildSitemap'...
[14:19:10] Finished 'buildSitemap' after 2.53 ms
[14:19:10] Starting 'build'...
[14:19:10] Finished 'build' after 29 μs
[14:19:10] Starting 'deploy'...
writing sitemap
(node:43995) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[14:19:10] [gh-pages (master)] Cloning repo
[14:19:10] [gh-pages (master)] Checkout branch `master`
[14:19:11] [gh-pages (master)] Updating repository
[14:19:11] [gh-pages (master)] Copying files to repository
[14:19:12] [gh-pages (master)] No files have changed.
[14:19:12] Finished 'deploy' after 1.44 s
```

I think `glob` is async. I'm looking into a fix now.

**Comment by ctalkington** [comment]
@jarrodtaylor  ah i had wondered if i was something like that. maybe you can use `glob.sync` vs `glob`?

**Pull request merged**
